# Generated by Django 4.1.3 on 2022-11-11 21:32

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to='static/img', variations={'thumb': (300, 300)}, verbose_name='Imagem'),
        ),
    ]
